# TensorFlow
### 데이터를 전처리하고, 모델링하고, 서비스까지 도와주는 오픈소스 머신러닝 라이브러리

In [3]:
!python --version

Python 3.7.15


In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [4]:
# scalar (스칼라) rank가 0인 tensor
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim  # number of dimensions

0

In [8]:
# vector (벡터) 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [10]:
vector = tf.constant([10])
vector

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>

In [11]:
vector.ndim

1

In [12]:
# matrix (행렬) 
matrix = tf.constant([
    [10, 7],
    [7, 10]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:
matrix.ndim

2

In [15]:
# 현재까지 정수를 사용하였는데 tensorflow는 기본적으로 정수를 다룰 때 int32를 자료형으로 사용한다.
# 실수를 다룰 때는 float32를 자료형으로 사용한다.
# 각 자료형 뒤의 숫자는 precision을 의미하는데... 숫자가 클수록 정밀도는 높아진다!
# 그만큼 PC의 메모리를 많이 사용한다!

In [18]:
another_matrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [19]:
another_matrix.ndim

2

In [20]:
another_matrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [21]:
another_matrix.ndim

2

In [22]:
# 2행 3열짜리 행렬을 3개 만든다!
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]        
    ],
    [
        [13, 14, 15],
        [16, 17, 18]        
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [23]:
tensor.ndim

3

In [24]:
# rank가 3인 tensor를 만들었다! 3차원 tensor를 만들었다! 
# 결국 tensor는 임의의 차원을 가질 수 있다!
# scalar, vector, matrix는 0, 1, 2의 차원을 가진 tensor의 특별한 이름이다!
# tensor : n-차원 배열이다! (n은 임의의 숫자!)

In [26]:
# tf.Variable() : mutable (변경할 수 있다)
# tf.constant() : immutable (변경할 수 없다)

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [28]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [29]:
changeable_tensor[0] = 7

TypeError: ignored

In [31]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [32]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [33]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [34]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

In [35]:
# tf.constant() or tf.Variable() 
# 우리가 해결하려는 문제 및 데이터에 따라서, 어떤 것을 사용할지 결정이 되고,
# 대부분의 경우 tensorflow가 알아서 데이터를 불러오거나 모델링할 때 처리를 해줍니다.

In [36]:
random_1 = tf.random.Generator.from_seed(42)  # 임의의 값을 선택하는 스타일, 방식을 42 형식으로 만들어달라! 재현을 하기 위해서!
random_1 = random_1.normal( shape = (3, 2) )  # 임의의 값은 선택을 하더라도 정규 분포에서 값을 가져와라!

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal( shape = (3, 2) )

In [37]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [38]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [39]:
# NumPy에서는 np.random.seed(42)

In [40]:
random_3 = tf.random.Generator.from_seed(42) 
random_3 = random_3.normal( shape = (3, 2) ) 

random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal( shape = (3, 2) )

In [41]:
random_3, random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.2829171 ]], dtype=float32)>)

In [42]:
random_3 == random_4

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [43]:
random_1 == random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [44]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [64]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [65]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [66]:
# tf.random.set_seed(42) : global seed
# tf.random.shuffle(seed = 42) : operation seed

In [72]:
tf.random.set_seed(42)

In [79]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [81]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [88]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### Tensor를 만드는 다양한 방법들



In [89]:
tf.ones( shape = (3, 2) )

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [90]:
tf.zeros( shape = (3, 2) )

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [91]:
# NumPy로 다룰 것을 왜 tensor로 다루느냐... => tensor는 GPU에서 실행할 수 있다!

In [92]:
import numpy as np

In [93]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [94]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [95]:
A.ndim

1

In [96]:
A = tf.constant(numpy_A, shape = [2, 4, 3])
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [97]:
rank_4_tensor = tf.zeros( [2, 3, 4, 5] )
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [98]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [99]:
rank_4_tensor.ndim

4

In [100]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [101]:
print("모든 원소들의 데이터형은 ", rank_4_tensor.dtype)
print("차원 (dimension or rank)은 ", rank_4_tensor.ndim)
print("tensor의 shape는 ", rank_4_tensor.shape)
print("tensor의 axis 0의 값은 ", rank_4_tensor.shape[0])
print("tensor의 마지막 axis의 값은 ", rank_4_tensor.shape[-1])
print("tensor를 이루는 모든 원소들의 갯수는 ", tf.size(rank_4_tensor))

모든 원소들의 데이터형은  <dtype: 'float32'>
차원 (dimension or rank)은  4
tensor의 shape는  (2, 3, 4, 5)
tensor의 axis 0의 값은  2
tensor의 마지막 axis의 값은  5
tensor를 이루는 모든 원소들의 갯수는  tf.Tensor(120, shape=(), dtype=int32)


In [102]:
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [103]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [104]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [105]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])

In [106]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [107]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]  # ... 의 의미는 기존의 tensor의 axis는 유지하면서 뒤에 추가로 axis를 추가
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [108]:
rank_2_tensor.ndim

2

In [109]:
rank_3_tensor.ndim

3

In [110]:
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [111]:
tf.expand_dims(rank_2_tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### tensor 처리하기 (manipulating)

In [113]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [114]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [116]:
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [117]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [118]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [120]:
tf.multiply(tensor, 10)  # 실제 연산에서 연산자를 사용하는 것보다 조금 더 성능의 이점을 가질 수 있다.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [122]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [123]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix multiplication

#### Matrix Multiplication에서 기억해야할 2가지 법칙

1. 연산시 안쪽의 dimension은 일치해야 한다.
* (3, 5) @ (3, 5) : 실행 안 됨
* (5, 3) @ (3, 5) : 실행 됨
* (3, 5) @ (5, 3) : 실행 됨

2. 실행의 결과는 바깥쪽의 dimension의 shape를 가진다.
* (5, 3) @ (3, 5) -> (5, 5)
* (3, 5) @ (5, 3) -> (3, 3)

@ : 파이썬에서 matrix multiplication을 의미!

In [124]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [125]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [126]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [127]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [128]:
X @ Y  # (3, 2) @ (3, 2)

InvalidArgumentError: ignored

In [130]:
# (2, 3) @ (3, 2)
# (3, 2) @ (2, 3)

# tf.reshape() : tensor의 모양을 지정한 shape의 형태로 바꾸고 순서대로 원소의 값을 채운다.
# tf.transpose() : 주어진 tensor의 차원을 바꾸어 준다

In [132]:
tf.reshape(Y, shape = (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [133]:
X.shape

TensorShape([3, 2])

In [134]:
X @ tf.reshape(Y, shape = (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [136]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [135]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [138]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [137]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [139]:
tf.matmul(X, Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### dot product

In [141]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [142]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [143]:
B = tf.constant([1.7, 7.4])
C = tf.constant([1, 7])

B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [144]:
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [145]:
C = tf.cast(C, dtype = tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [146]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [147]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [148]:
tf.math.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### aggregation 함수 

In [149]:
E = tf.constant(np.random.randint(low = 0, high = 100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([61,  0, 36,  7, 49, 22, 22, 98, 24, 67, 75, 70, 75, 74, 14, 96, 60,
       97, 98, 18,  0,  9, 54, 12, 87,  8, 47, 22, 94, 26, 18, 93,  5, 73,
       97, 46, 47, 30, 62,  7, 44, 98, 39, 11, 30, 11, 20, 13, 63, 30])>

In [150]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [151]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [152]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [153]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2259>

In [156]:
tf.math.reduce_std( tf.cast(E, dtype=tf.float16) )

<tf.Tensor: shape=(), dtype=float16, numpy=31.78>

In [159]:
tf.math.reduce_variance( tf.cast(E, dtype=tf.float16) )

<tf.Tensor: shape=(), dtype=float16, numpy=1010.0>

In [161]:
# ["Green", "Blue", "Red"]
# [0.98, 0.01, 0.01]   # Green 98% / Blue 1% / Red 1%

# tf.argmax()
# tf.argmin()

In [162]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([5.69515041e-01, 5.16651909e-01, 1.15491580e-01, 5.71669525e-01,
       8.82729140e-01, 8.93985966e-01, 1.37486290e-01, 4.14942153e-01,
       1.02214119e-01, 4.28573965e-01, 1.39328501e-01, 6.48307468e-04,
       2.30334479e-01, 2.61018016e-01, 7.06565081e-01, 2.73852342e-01,
       3.04910925e-01, 3.87605293e-01, 9.10489485e-02, 7.90407300e-01,
       8.60406587e-01, 7.36870342e-01, 5.92318053e-02, 7.48142163e-01,
       2.49660154e-01, 2.11880670e-01, 5.04279723e-01, 2.69049741e-01,
       5.88523515e-01, 4.58132985e-01, 9.61243174e-01, 8.14352932e-01,
       7.33558699e-01, 2.30578254e-01, 5.10533987e-01, 5.15114796e-02,
       2.45124043e-01, 1.06306000e-01, 7.69951957e-01, 8.27504568e-01,
       6.20943202e-01, 3.80371163e-02, 4.92343326e-01, 6.61325923e-02,
       8.84717497e-01, 8.21811982e-01, 6.12537111e-01, 7.58476527e-01,
       1.33883354e-03, 2.30885510e-02])>

In [163]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.961243174057535>

In [164]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [165]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0006483074677403611>

In [166]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [167]:
tf.argmax(F).numpy()

30

In [168]:
tf.argmin(F).numpy()

11

In [169]:
F[ tf.argmax(F).numpy() ]

<tf.Tensor: shape=(), dtype=float64, numpy=0.961243174057535>

In [170]:
F[ tf.argmin(F).numpy() ]

<tf.Tensor: shape=(), dtype=float64, numpy=0.0006483074677403611>

In [171]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[ 7, 76,  3, 39, 97, 52, 54, 91,  2, 31, 74, 90, 12, 35, 96,
           93, 24,  6, 58, 24, 15,  9, 37, 44,  5, 56, 38, 54, 33, 37,
           11, 77,  5, 96, 84, 85, 63, 20,  3, 67, 10, 48, 88,  7, 25,
           18, 46, 98, 41, 78]]]]])>

In [173]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [172]:
G[0][0][0][0]

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 7, 76,  3, 39, 97, 52, 54, 91,  2, 31, 74, 90, 12, 35, 96, 93, 24,
        6, 58, 24, 15,  9, 37, 44,  5, 56, 38, 54, 33, 37, 11, 77,  5, 96,
       84, 85, 63, 20,  3, 67, 10, 48, 88,  7, 25, 18, 46, 98, 41, 78])>

In [175]:
G_squeeze = tf.squeeze(G)
G_squeeze.shape, G_squeeze.ndim

(TensorShape([50]), 1)

In [176]:
G_squeeze

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 7, 76,  3, 39, 97, 52, 54, 91,  2, 31, 74, 90, 12, 35, 96, 93, 24,
        6, 58, 24, 15,  9, 37, 44,  5, 56, 38, 54, 33, 37, 11, 77,  5, 96,
       84, 85, 63, 20,  3, 67, 10, 48, 88,  7, 25, 18, 46, 98, 41, 78])>

### One-Hot encoding

In [178]:
some_list = [0, 1, 2, 3]
some_list

[0, 1, 2, 3]

In [179]:
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [180]:
tf.one_hot(some_list, depth = 3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [181]:
tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [182]:
tf.one_hot(some_list, depth = 4, on_value = "On", off_value = "Off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>

In [183]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [184]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [185]:
tf.sqrt(H)

InvalidArgumentError: ignored

In [186]:
H = tf.cast(H, dtype = tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [187]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [188]:
tf.log(H)

AttributeError: ignored

In [189]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [192]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [193]:
I.assign( [0, 1, 2, 3, 50] )

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [194]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [195]:
I.assign_add( [10, 10, 10, 10, 10 ] )

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [196]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [202]:
# NumPy와 TensorFlow
# NumPy <---> TensorFlow
# np.array() : NumPy array을 얻기 위해서, np.array에 tensor를 전달한다!
# tensor.numpy() : tensor에게 NumPy array를 요청!

# 실수로 tensor를 만들 때, 기본 자료형은 float32! NumPy를 통해서 tensor를 만들면 float64!
# NumPy는 수치 연산에 특화 되었기 때문에 정밀도가 많이 필요하다.
# TensorFlow의 경우 신경망 (neural network)를 사용하고, 이 때 정밀도가 그다지 중요하지 않다!

In [198]:
J = tf.constant(np.array( [3., 7., 10.] ))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [199]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [201]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [203]:
def function(x, y):
  return x ** 2 + y

In [204]:
x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
x, y

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>)

In [205]:
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [206]:
@tf.function   # 같은 결과를 얻더라도 성능면에서 이점을 가질 수 있다.
def tf_function(x, y):
  return x ** 2 + y

In [207]:
tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

### GPU 사용하기

In [208]:
print(tf.config.list_physical_devices("GPU"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [209]:
!nvidia-smi

Sat Nov 12 02:21:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0    28W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------